<script setup>
import {Head} from '@inertiajs/vue3';import {computed,ref} from 'vue';import CustomerShell from '../../Components/CustomerShell.vue';
const props=defineProps({tool:String});
const matches=ref(100),winRate=ref(50),target=ref(60),zodiacPoints=ref(40),summonCost=ref(20),avgPoint=ref(2),magicPoints=ref(80),singleCost=ref(60),fiveCost=ref(270);
const meta=computed(()=>({ 'win-rate':['Kalkulator Win Rate','Hitung kemenangan beruntun untuk mencapai target win rate.'],zodiac:['Kalkulator Zodiac','Perkirakan summon dan diamond untuk mencapai 100 poin Zodiac.'],'magic-wheel':['Kalkulator Magic Wheel','Hitung kombinasi draw hemat untuk mencapai 200 Magic Point.']}[props.tool]||['Kalkulator','Alat bantu game']));
const wr=computed(()=>{const p=Math.max(0,+matches.value||0),c=Math.min(100,Math.max(0,+winRate.value||0))/100,d=Math.min(99.99,Math.max(0,+target.value||0))/100;if(!p||c>=d)return 0;return Math.max(0,Math.ceil(((d-c)*p)/(1-d)))});
const zodiac=computed(()=>{const rem=Math.max(0,100-Math.min(100,+zodiacPoints.value||0)),avg=Math.min(5,Math.max(1,+avgPoint.value||1)),draws=Math.ceil(rem/avg);return {draws,diamonds:draws*Math.max(0,+summonCost.value||0)}});
const magic=computed(()=>{const rem=Math.max(0,200-Math.min(200,+magicPoints.value||0));let best=Infinity,sets=0,singles=0;for(let s=0;s<=Math.ceil(rem/5);s++){const one=Math.max(0,rem-s*5),total=s*(+fiveCost.value||0)+one*(+singleCost.value||0);if(total<best){best=total;sets=s;singles=one}}return {best:Number.isFinite(best)?best:0,sets,singles,rem}});
</script>
<template><Head :title="meta[0]"/><CustomerShell><main class="lf-container lf-content-page"><p class="lf-eyebrow">KALKULATOR GAME</p><h1 class="lf-title">{{meta[0]}}</h1><p class="lf-copy">{{meta[1]}}</p><section class="lf-tool-card mt-6"><template v-if="tool==='win-rate'"><div class="lf-tool-fields"><label>Total pertandingan<input v-model.number="matches" type="number" min="0"></label><label>Win rate sekarang (%)<input v-model.number="winRate" type="number" min="0" max="100" step=".01"></label><label>Target win rate (%)<input v-model.number="target" type="number" min="0" max="99.99" step=".01"></label></div><div class="lf-tool-result"><small>Kemenangan beruntun yang dibutuhkan</small><strong>{{wr}} win</strong><p>Perkiraan total pertandingan setelah target: {{Number(matches)+wr}}.</p></div></template><template v-else-if="tool==='zodiac'"><div class="lf-tool-fields"><label>Poin Zodiac sekarang<input v-model.number="zodiacPoints" type="number" min="0" max="100"></label><label>Diamond per summon<input v-model.number="summonCost" type="number" min="0"></label><label>Rata-rata poin per summon<input v-model.number="avgPoint" type="number" min="1" max="5" step=".1"></label></div><div class="lf-tool-result"><small>Estimasi diamond</small><strong>{{zodiac.diamonds.toLocaleString('id-ID')}} diamond</strong><p>Sekitar {{zodiac.draws}} summon.</p></div></template><template v-else><div class="lf-tool-fields"><label>Magic Point sekarang<input v-model.number="magicPoints" type="number" min="0" max="200"></label><label>Harga 1 draw<input v-model.number="singleCost" type="number" min="0"></label><label>Harga 5 draw<input v-model.number="fiveCost" type="number" min="0"></label></div><div class="lf-tool-result"><small>Estimasi diamond termurah</small><strong>{{magic.best.toLocaleString('id-ID')}} diamond</strong><p>{{magic.sets}}× paket 5 draw dan {{magic.singles}}× single draw.</p></div></template><p class="lf-tool-note">Hasil adalah estimasi. Harga dan mekanisme game dapat berubah.</p></section></main></CustomerShell></template>