<script setup>
import {Link,usePage} from '@inertiajs/vue3';import {computed,ref} from 'vue';
defineProps({logoUrl:{type:String,default:''},compactFooter:{type:Boolean,default:false}});
const page=usePage(),open=ref(false),logged=computed(()=>Boolean(page.props.auth?.user));
</script><template><div class="lf-customer">
<header class="lf-header"><div class="lf-container lf-header-inner"><Link href="/" class="lf-brand"><span class="lf-brand-mark">LF</span><span><strong class="lf-brand-name">LFAMILIA</strong><span class="lf-brand-sub">STORE</span></span></Link><Link href="/#produk" class="lf-header-search">⌕ <span>Cari game atau voucher...</span></Link><nav class="lf-nav"><Link href="/">Top Up</Link><Link href="/orders/check">Cek Pesanan</Link><Link href="/account">Akun</Link></nav><div class="ml-auto flex gap-1.5"><Link href="/account" class="lf-action">◉ Akun</Link><Link v-if="!logged" href="/login" class="lf-action">↪ Masuk</Link><button class="lf-menu" @click="open=true">☰</button></div></div></header>
<div v-if="open" class="lf-overlay" @click="open=false"></div><aside v-if="open" class="lf-drawer"><div class="flex items-center justify-between"><div class="lf-brand"><span class="lf-brand-mark">LF</span><strong>LFAMILIA STORE</strong></div><button class="lf-menu !grid" @click="open=false">×</button></div><div class="mt-4 rounded-xl border border-white/10 bg-white/[.035] p-3"><p class="text-[9px] font-black uppercase tracking-[.18em] text-[#cfff72]">{{logged?'Akun aktif':'Selamat datang'}}</p><p class="mt-1 text-[11px] leading-4 text-white/50">{{logged?'Kelola saldo, pesanan, membership, tiket dan profilmu.':'Masuk untuk pengalaman top up yang lebih cepat.'}}</p><Link :href="logged?'/account':'/login'" class="lf-primary mt-3 w-full" @click="open=false">{{logged?'Buka Akun':'Masuk'}}</Link></div><nav><Link href="/" @click="open=false">Beranda</Link><Link href="/orders/check" @click="open=false">Cek Pesanan</Link><Link href="/account" @click="open=false">Akun Saya</Link><Link v-if="!logged" href="/register" @click="open=false">Daftar</Link></nav></aside>
<slot/>
<footer v-if="!compactFooter" class="lf-footer"><div class="lf-container lf-footer-grid"><div><div class="lf-brand"><span class="lf-brand-mark">LF</span><span><strong class="lf-brand-name">LFAMILIA</strong><span class="lf-brand-sub">STORE</span></span></div><p class="mt-4 max-w-sm text-[11px] leading-5 text-white/40">Top up game dan produk digital dengan alur transaksi yang cepat, aman, dan transparan.</p></div><div><h2>Layanan</h2><ul><li><Link href="/#produk">Top Up Game</Link></li><li><Link href="/orders/check">Cek Transaksi</Link></li></ul></div><div><h2>Akun</h2><ul><li><Link href="/login">Masuk</Link></li><li><Link href="/register">Daftar</Link></li><li><Link href="/forgot-password">Lupa Password</Link></li></ul></div><div><h2>Informasi</h2><ul><li><Link href="/account/tickets">Layanan Pelanggan</Link></li><li><Link href="/account/membership">Membership</Link></li></ul></div></div><div class="lf-footer-copy">© 2026 LFAMILIA STORE.</div></footer>
</div></template>