import { LegalPage } from "@/components/legal-page";

export default function PrivacyPage() {
  return <LegalPage
    eyebrow="Dokumen hukum"
    title="Kebijakan Privasi"
    intro="Kebijakan ini menjelaskan bagaimana LFAMILIA STORE mengumpulkan, menggunakan, membagikan, menyimpan, dan melindungi informasi saat kamu mengakses website, membuat akun, bertransaksi, atau menghubungi bantuan."
    highlights={[
      "Data digunakan untuk memproses pesanan, menjaga keamanan, dan memberikan bantuan.",
      "LFAMILIA tidak menjual atau menyewakan data pribadi pengguna.",
      "Jangan pernah mengirim password, PIN, atau kode OTP melalui formulir bantuan.",
    ]}
    sections={[
      { title: "Ruang lingkup dan persetujuan", paragraphs: ["Kebijakan ini berlaku untuk seluruh halaman dan layanan LFAMILIA STORE. Dengan menggunakan layanan, kamu memahami pemrosesan informasi sebagaimana dijelaskan di dokumen ini. Jika tidak menyetujui ketentuannya, hentikan penggunaan layanan dan jangan mengirimkan data pribadi."] },
      { title: "Informasi yang kami kumpulkan", paragraphs: ["Jenis informasi bergantung pada fitur yang kamu gunakan. Kami hanya meminta data yang relevan untuk transaksi, keamanan, atau bantuan."], items: ["Data identitas dan kontak, seperti nama, alamat email, serta nomor WhatsApp.", "Data akun jika kamu mendaftar, termasuk informasi profil dan riwayat aktivitas akun.", "Data tujuan produk digital, seperti User ID, server, nickname, email penerima, atau nomor tujuan.", "Data transaksi, seperti nomor invoice, produk, nominal, waktu, status, metode pembayaran, dan referensi pembayaran. Kami tidak meminta PIN, OTP, atau kata sandi pembayaran.", "Data komunikasi yang kamu kirim kepada tim bantuan, termasuk isi pesan dan lampiran pendukung.", "Data teknis dan keamanan, seperti alamat IP, jenis perangkat, browser, waktu akses, serta catatan sistem yang diperlukan untuk mencegah penyalahgunaan."] },
      { title: "Cara kami menggunakan informasi", items: ["Membuat, memverifikasi, memproses, dan mengirim pesanan.", "Menampilkan riwayat serta status transaksi dan menyampaikan pemberitahuan terkait pesanan.", "Menjawab pertanyaan, menangani keluhan, dan meninjau permintaan refund.", "Mencegah penipuan, transaksi tidak sah, spam, dan gangguan terhadap sistem.", "Menjaga, mengevaluasi, dan meningkatkan keamanan, keandalan, serta pengalaman website.", "Memenuhi kewajiban administrasi, akuntansi, penyelesaian sengketa, dan ketentuan hukum yang berlaku."] },
      { title: "Dasar pemrosesan", paragraphs: ["Kami memproses informasi ketika diperlukan untuk memenuhi pesanan atau permintaanmu, berdasarkan persetujuan yang kamu berikan, untuk menjaga kepentingan keamanan yang wajar, atau untuk memenuhi kewajiban hukum. Persetujuan dapat ditarik untuk pemrosesan yang memang bergantung pada persetujuan, tanpa memengaruhi pemrosesan yang telah dilakukan sebelumnya."] },
      { title: "Pembagian data kepada pihak lain", paragraphs: ["Informasi dapat dibagikan secara terbatas kepada pihak yang membantu menjalankan layanan. Mereka hanya menerima data yang diperlukan untuk tugas terkait."], items: ["Penyedia pembayaran untuk memverifikasi dan menyelesaikan pembayaran atau refund.", "Pemasok produk digital, distributor, atau publisher untuk memproses tujuan dan nominal pesanan.", "Penyedia hosting, keamanan, analitik teknis, serta komunikasi untuk menjaga operasional layanan.", "Penasihat profesional atau instansi berwenang apabila diwajibkan oleh hukum atau diperlukan untuk melindungi hak dan keamanan.", "Pihak penerus usaha apabila terjadi penggabungan atau pengalihan usaha yang sah, dengan perlindungan data yang tetap berlaku."] },
      { title: "Cookie dan penyimpanan lokal", paragraphs: ["Website dapat menggunakan cookie atau penyimpanan lokal untuk mempertahankan sesi masuk, menyimpan preferensi, menjaga keranjang, mengukur performa, dan mendeteksi aktivitas berisiko. Kamu dapat membatasi cookie melalui browser, tetapi beberapa fungsi website mungkin tidak bekerja dengan benar."] },
      { title: "Penyimpanan dan masa retensi", paragraphs: ["Data disimpan selama dibutuhkan untuk menyediakan layanan, menyelesaikan transaksi, menangani sengketa, mencegah penipuan, dan memenuhi kewajiban pencatatan. Setelah tidak diperlukan, data akan dihapus, dianonimkan, atau dibatasi penggunaannya sesuai kemampuan teknis dan ketentuan yang berlaku."] },
      { title: "Keamanan informasi", paragraphs: ["Kami menerapkan pembatasan akses, validasi, pencatatan aktivitas, dan perlindungan teknis yang wajar. Namun, tidak ada pengiriman atau penyimpanan melalui internet yang sepenuhnya bebas risiko. Pengguna wajib menjaga keamanan akun, perangkat, serta informasi masuknya sendiri dan segera melapor jika menemukan aktivitas mencurigakan."] },
      { title: "Hak dan pilihan pengguna", paragraphs: ["Kamu dapat meminta informasi, koreksi, pembaruan, atau penghapusan data pribadi melalui kanal bantuan resmi. Kami dapat meminta verifikasi identitas terlebih dahulu. Permintaan dapat dibatasi jika data masih diperlukan untuk transaksi, keamanan, pencegahan penipuan, pembelaan hak, atau kewajiban hukum."] },
      { title: "Data anak dan pengguna di bawah umur", paragraphs: ["Layanan tidak ditujukan untuk anak yang belum dapat memberikan persetujuan secara sah. Pengguna di bawah umur wajib menggunakan layanan dengan izin dan pengawasan orang tua atau wali. Jika kami mengetahui data anak dikirim tanpa izin yang semestinya, kami dapat menghapus atau membatasi data tersebut."] },
      { title: "Tautan dan layanan pihak ketiga", paragraphs: ["Website dapat memuat tautan atau terhubung ke layanan pihak ketiga, termasuk penyedia pembayaran dan publisher game. Praktik privasi pihak tersebut berada di luar kendali LFAMILIA STORE; bacalah kebijakan mereka sebelum memberikan informasi."] },
      { title: "Perubahan dan kontak", paragraphs: ["Kebijakan ini dapat diperbarui saat layanan, mitra, atau ketentuan berubah. Versi terbaru selalu ditampilkan di halaman ini beserta tanggal pembaruannya. Pertanyaan atau permintaan terkait privasi dapat diajukan melalui halaman Hubungi Kami dan kanal resmi yang tercantum di sana."] },
    ]}
  />;
}
