"use client";

import { useCallback, useEffect, useState } from "react";
import { LoaderCircle, MessageCircleMore, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

type Item = { id: string; kind: string; order_reference: string | null; subject: string; message: string; status: string; staff_reply: string | null; created_at: string; customer_name: string; customer_email: string };

export function AdminSupportManager() {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [saving, setSaving] = useState<string | null>(null); const [reply, setReply] = useState<Record<string, string>>({}); const [status, setStatus] = useState<Record<string, string>>({});
  const load = useCallback(async () => { try { const response = await fetch("/api/panel/support", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.requests ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Bantuan gagal dimuat."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(item: Item) { setSaving(item.id); try { const response = await fetch("/api/panel/support", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, status: status[item.id] ?? item.status, reply: reply[item.id] ?? item.staff_reply ?? "" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Balasan gagal disimpan."); } finally { setSaving(null); } }
  if (loading) return <div className="flex min-h-40 items-center justify-center text-xs text-white/35"><LoaderCircle className="mr-2 size-4 animate-spin" />Memuat bantuan…</div>;
  return <div>{error && <p className="mb-4 rounded-xl border border-red-400/20 bg-red-400/[0.06] p-3 text-xs text-red-200">{error}</p>}<div className="space-y-3">{items.length ? items.map((item) => <article key={item.id} className="rounded-2xl border border-white/[0.08] bg-white/[0.02] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#b9ff35]/10 text-[#cfff72]"><MessageCircleMore className="size-4" /></span><div><span className="text-[9px] font-black uppercase tracking-wider text-[#cfff72]">{item.kind === "refund" ? "Refund" : "Bantuan"}</span><h3 className="mt-1 text-sm font-bold">{item.subject}</h3><p className="mt-1 text-[10px] text-white/35">{item.customer_name} • {item.customer_email}{item.order_reference ? ` • ${item.order_reference}` : ""}</p></div></div><select value={status[item.id] ?? item.status} onChange={(event) => setStatus((current) => ({ ...current, [item.id]: event.target.value }))} className="h-9 rounded-lg border border-white/10 bg-[#171c27] px-2 text-xs text-white"><option value="open">Menunggu</option><option value="in_progress">Diproses</option><option value="resolved">Selesai</option><option value="rejected">Ditolak</option></select></div><p className="mt-4 whitespace-pre-wrap text-xs leading-5 text-white/60">{item.message}</p><Textarea value={reply[item.id] ?? item.staff_reply ?? ""} onChange={(event) => setReply((current) => ({ ...current, [item.id]: event.target.value }))} className="mt-4 min-h-20 rounded-xl border-white/10 bg-white/[0.025] text-xs text-white" placeholder="Tulis balasan untuk pelanggan…" /><div className="mt-3 flex justify-end"><Button onClick={() => void save(item)} disabled={saving === item.id} className="rounded-xl bg-[#b9ff35] text-xs font-black text-[#091006]">{saving === item.id ? <LoaderCircle className="mr-2 size-4 animate-spin" /> : <Save className="mr-2 size-4" />}Simpan balasan</Button></div></article>) : <div className="rounded-xl border border-dashed border-white/10 py-10 text-center text-xs text-white/30">Belum ada permintaan bantuan atau refund.</div>}</div></div>;
}
