import { LegalPage } from "@/components/legal-page";

export default function TermsPage() {
  return <LegalPage
    eyebrow="Dokumen hukum"
    title="Syarat & Ketentuan"
    intro="Syarat ini mengatur penggunaan website dan pembelian produk digital di LFAMILIA STORE. Dengan mengakses layanan atau membuat pesanan, kamu menyatakan telah membaca, memahami, dan menyetujui ketentuan berikut."
    highlights={[
      "Periksa produk, nominal, User ID, dan server sebelum membayar.",
      "Pesanan digital yang sudah berhasil dikirim umumnya tidak dapat dibatalkan.",
      "LFAMILIA tidak pernah meminta password, PIN, atau kode OTP.",
    ]}
    sections={[
      { title: "Penerimaan ketentuan", paragraphs: ["Ketentuan ini berlaku bagi pengunjung, pemilik akun, dan pembeli. Jika kamu menggunakan layanan atas nama pihak lain, kamu menyatakan memiliki izin untuk melakukannya. Apabila tidak menyetujui ketentuan ini, jangan melanjutkan transaksi."] },
      { title: "Ruang lingkup layanan", paragraphs: ["LFAMILIA STORE menyediakan sarana pembelian top up game, voucher, lisensi, dan produk digital lain yang ditampilkan di katalog. Nama, logo, dan merek game tetap dimiliki pemegang hak masing-masing. Ketersediaan produk bergantung pada pemasok, publisher, wilayah, dan kondisi sistem."] },
      { title: "Akun dan keamanan", items: ["Berikan informasi yang benar dan mutakhir ketika membuat akun atau memesan.", "Jaga kerahasiaan kredensial akun dan seluruh aktivitas yang terjadi melalui akunmu.", "Segera hubungi bantuan jika menduga akun digunakan tanpa izin.", "Pengguna di bawah umur wajib memperoleh izin orang tua atau wali.", "Jangan memasukkan password game, PIN pembayaran, kode OTP, atau data kartu ke kolom pesanan dan formulir bantuan."] },
      { title: "Informasi produk dan harga", paragraphs: ["Deskripsi, nominal, wilayah, persyaratan, dan estimasi proses ditampilkan pada halaman produk. Harga dapat berubah mengikuti pemasok atau promosi. Harga yang berlaku adalah harga pada ringkasan pesanan saat invoice dibuat, kecuali terjadi kesalahan tampilan yang nyata atau manipulasi sistem."] },
      { title: "Pembayaran", paragraphs: ["Pesanan diproses setelah pembayaran terverifikasi. Total akhir, termasuk biaya kanal pembayaran jika ada, ditampilkan sebelum pembayaran dibuat. Pengguna wajib memakai sumber dana dan metode pembayaran yang sah. Invoice yang tidak dibayar sampai kedaluwarsa dapat dibatalkan otomatis."] },
      { title: "Data tujuan dan tanggung jawab pengguna", paragraphs: ["Kamu bertanggung jawab memeriksa User ID, server, zona, email, nomor telepon, region, dan data tujuan lain sebelum membayar. Sistem memproses data persis seperti yang dikirim. Pesanan yang berhasil dikirim ke tujuan yang salah karena kesalahan pengguna umumnya tidak dapat ditarik atau dipindahkan."] },
      { title: "Pemrosesan dan pengiriman", paragraphs: ["Produk otomatis diteruskan ke penyedia setelah pembayaran terverifikasi. Produk manual mengikuti antrean dan petunjuk yang tercantum pada halaman produk. Status berhasil dari sistem, pemasok, atau admin merupakan bukti bahwa produk telah diproses ke data tujuan. Waktu proses adalah estimasi dan dapat bertambah saat terjadi antrean atau gangguan pihak ketiga."] },
      { title: "Voucher, kode, dan produk manual", items: ["Periksa wilayah, platform, dan masa berlaku voucher sebelum membeli.", "Kode yang sudah ditampilkan, dikirim, atau digunakan dianggap telah diserahkan.", "Jaga kerahasiaan kode; risiko akibat kode dibagikan setelah pengiriman menjadi tanggung jawab penerima.", "Untuk produk manual, ikuti instruksi dengan benar dan hanya kirim data yang memang diminta pada halaman produk."] },
      { title: "Larangan penggunaan", items: ["Menggunakan dana, akun, identitas, atau metode pembayaran tanpa izin.", "Melakukan manipulasi harga, eksploitasi celah, bot yang mengganggu, serangan, atau akses tanpa wewenang.", "Menyalahgunakan promo, membuat transaksi palsu, melakukan penipuan, atau chargeback yang tidak berdasar.", "Menggunakan layanan untuk aktivitas yang melanggar hukum, hak pihak lain, atau ketentuan publisher."] },
      { title: "Pembatalan dan refund", paragraphs: ["Pesanan yang belum dibayar dapat berakhir otomatis. Setelah pembayaran atau pemrosesan dimulai, pembatalan hanya dapat dilakukan jika memenuhi Kebijakan Refund. Pengajuan chargeback tanpa terlebih dahulu menghubungi bantuan dapat menyebabkan transaksi dan akun ditinjau untuk mencegah penyalahgunaan."] },
      { title: "Gangguan dan perubahan layanan", paragraphs: ["Pemeliharaan, kegagalan jaringan, keterlambatan pembayaran, gangguan pemasok atau publisher, perubahan kebijakan game, dan keadaan di luar kendali wajar dapat menyebabkan penundaan atau ketidaktersediaan. Kami dapat menyesuaikan, menangguhkan, atau menghentikan produk tertentu untuk menjaga keamanan dan operasional."] },
      { title: "Batas tanggung jawab", paragraphs: ["LFAMILIA bertanggung jawab menangani pesanan sesuai informasi yang diterima dan kebijakan yang berlaku. Sejauh diizinkan hukum, tanggung jawab atas klaim transaksi dibatasi pada nilai pesanan terkait. Kami tidak bertanggung jawab atas kerugian tidak langsung, perubahan akun oleh publisher, hilangnya bonus pihak ketiga, atau kerugian akibat kesalahan data dan tindakan pengguna."] },
      { title: "Hak kekayaan intelektual", paragraphs: ["Konten, identitas, tata letak, dan materi milik LFAMILIA tidak boleh disalin atau digunakan untuk menyesatkan tanpa izin. Materi game dan produk pihak ketiga digunakan untuk identifikasi katalog dan tetap menjadi hak pemilik merek masing-masing."] },
      { title: "Perubahan, hukum, dan kontak", paragraphs: ["Ketentuan dapat diperbarui untuk menyesuaikan layanan, mitra, risiko, atau peraturan. Versi terbaru berlaku sejak ditampilkan beserta tanggal pembaruannya. Ketentuan ini ditafsirkan berdasarkan hukum Republik Indonesia. Pertanyaan dan sengketa sebaiknya disampaikan terlebih dahulu melalui kanal bantuan resmi untuk dicari penyelesaian secara wajar."] },
    ]}
  />;
}
