<script setup>
import {Head,Link,router} from '@inertiajs/vue3';import {computed,ref} from 'vue';import CustomerShell from '../../Components/CustomerShell.vue';
const p=defineProps({categories:Array,products:Object,filters:Object,logoUrl:String,bannerUrl:String,mobileBannerUrl:String,popupUrl:String,faviconUrl:String,bannerTarget:String});const pop=ref(true),search=ref(p.filters.q??''),popular=computed(()=>(p.products?.data??[]).slice(0,8));const q=(x={})=>{const a={...p.filters,...x};Object.keys(a).forEach(k=>{if(!a[k])delete a[k]});const s=new URLSearchParams(a).toString();return s?'/?'+s:'/'};const submit=()=>router.get('/',{...p.filters,q:search.value},{preserveState:true});const initial=n=>(n||'L').slice(0,1).toUpperCase();const label=l=>String(l).includes('Previous')?'‹':String(l).includes('Next')?'›':String(l).replace(/&laquo;|&raquo;/g,'').trim();
</script><template><Head title="LFAMILIA STORE"/><CustomerShell :logo-url="logoUrl"><main>
<section v-if="bannerUrl||mobileBannerUrl" class="lf-container lf-banner"><div class="lf-banner-frame"><a v-if="bannerTarget" :href="bannerTarget"><picture><source v-if="mobileBannerUrl" media="(max-width:640px)" :srcset="mobileBannerUrl"><img :src="bannerUrl||mobileBannerUrl" alt="Banner LFAMILIA"></picture></a><picture v-else><source v-if="mobileBannerUrl" media="(max-width:640px)" :srcset="mobileBannerUrl"><img :src="bannerUrl||mobileBannerUrl" alt="Banner LFAMILIA"></picture></div></section>
<div v-if="popupUrl&&pop" class="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-4"><div class="max-w-lg rounded-xl bg-[#0d1019] p-2"><button class="lf-secondary mb-2" @click="pop=false">Tutup</button><img :src="popupUrl" class="max-h-[70vh] w-full object-contain"></div></div>
<section v-if="popular.length" class="lf-container lf-section pb-2"><p class="lf-eyebrow">🔥 Populer sekarang!</p><p class="lf-copy !mt-0">Berikut adalah beberapa produk yang paling populer saat ini.</p><div class="lf-popular"><Link v-for="x in popular" :key="x.slug" :href="'/catalog/'+x.slug" class="lf-popular-card"><span class="lf-popular-art"><img v-if="x.image_url" :src="x.image_url"><span v-else>{{initial(x.name)}}</span></span><span><strong>{{x.name}}</strong><small>{{x.category_name}}</small></span></Link></div></section>
<section id="produk" class="lf-container lf-section"><div class="lf-browser-head"><div><p class="lf-eyebrow">Otomatis & manual</p><h1 class="lf-title">Pilih produk favoritmu</h1><p class="lf-copy">Top up game, voucher, hiburan, pulsa, PLN, dan produk digital langsung dari halaman utama.</p></div><form class="lf-search" @submit.prevent="submit"><input v-model="search" placeholder="Cari game, voucher, pulsa, PLN..."></form></div><nav class="lf-filters"><Link :href="q({category:'',mode:''})" class="lf-chip" :class="{active:!filters.category&&!filters.mode}">Semua</Link><Link :href="q({category:'',mode:'manual'})" class="lf-chip" :class="{active:filters.mode==='manual'}">Produk Manual</Link><Link v-for="c in categories" :key="c.slug" :href="q({category:c.slug,mode:''})" class="lf-chip" :class="{active:filters.category===c.slug}">{{c.name}}</Link></nav><div v-if="products.data.length" class="lf-products"><Link v-for="x in products.data" :key="x.slug" :href="'/catalog/'+x.slug" class="lf-product"><img v-if="x.image_url" :src="x.image_url"><span v-else class="lf-product-fallback"><strong>{{x.name}}</strong><small>{{x.category_name}}</small></span></Link></div><p v-else class="mt-6 text-center text-sm text-white/40">Produk tidak ditemukan.</p><nav v-if="products.links?.length>3" class="lf-pages"><template v-for="x in products.links" :key="x.label"><Link v-if="x.url" :href="x.url" :class="{active:x.active}">{{label(x.label)}}</Link><span v-else>{{label(x.label)}}</span></template></nav></section>
<section class="lf-steps"><div class="lf-container lf-section"><p class="lf-eyebrow">Cara top up</p><h2 class="lf-title">Empat langkah sederhana</h2><div class="lf-step-grid"><article v-for="s in [['01','Pilih produk','Cari game atau produk digital yang kamu inginkan.'],['02','Isi data','Masukkan ID dan pilih nominal top up.'],['03','Bayar aman','Selesaikan pembayaran sesuai total pesanan.'],['04','Pesanan diproses','Pantau status menggunakan nomor pesanan.']]" :key="s[0]" class="lf-step"><span>{{s[0]}}</span><h3>{{s[1]}}</h3><p>{{s[2]}}</p></article></div></div></section>
<section class="lf-container lf-section"><div class="lf-help"><div><p class="lf-eyebrow">Butuh bantuan?</p><h2 class="m-0 text-[22px] font-black">Tim LFAMILIA siap membantu.</h2><p class="lf-copy">Sampaikan pertanyaan mengenai produk, pembayaran, atau status pesanan.</p></div><Link href="/account/tickets" class="lf-primary">Layanan Pelanggan</Link></div></section>
</main></CustomerShell></template>